### PR TITLE
fix: useId backward compatibility

### PR DESCRIPTION
**Pull request by phsantiago**
Projects not using react 18 are not able to use CMDK lib. #162 

This PR implements retro-compatibility for one of the hooks from React 18 used by the lib.

### CODE REVIEW

**Comment by gnapse** [comment]
Any word on the possibility to have this contribution accepted?

**Comment by LudovicGen** [comment]
Hello @pacocoursey and the team,

Just a quick follow up on PR #165 for React backwards compatibility. Any news on its evaluation?

**Review by LudovicGen — APPROVED** [review]

**Comment by julienba** [comment]
Hi, that would be great if you could merge this :)

**Comment by phsantiago** [comment]
Thank for the comment @pacocoursey.
I fix some problems from the previous version:
- It was generating a new id every render. Fixed with useState
- It wasn't using useId from react when available. Fixed by checking it before using

> Try testing on the preview deployment — everything is broken. 

Could you test again? Now seems to be working fine.
Should I duplicate the tests for running in react-16? Because now all tests passes but they are not using the compatibility code

>I believe React.useId is a strict requirement for this package to work in the way that it does.

The only problem I couldn't solve was to have same Id from the ones server side generated, but all the rest is working fine now.

**Comment by ntheanh201** [comment]
LGTM, I'm using the way you solved it to project running React 17

**Comment by callamwilliams** [comment]
Any movement on this? Would be extremely useful

**Review by nmigueles — APPROVED** [review]

**Review by pacocoursey — APPROVED** [review]
It does seem like this actually works, thanks!

**Comment by rafaell-lycan** [comment]
@phsantiago how about the `useSyncExternalStore`, have you found a decent work around for it?

**Comment by gnapse** [comment]
This is great. Thanks!

May I ask, when is this is expected to make it to a new package release?

**Comment by ananth99** [comment]
Currently working on a project with React 16 and want to know when will the changes be available for release?

**Comment by varatep** [comment]
Heya @pacocoursey - bump on this, are we able to get a new release out that includes this change to accommodate React versions under 18? Is there anything else that needs to be done?

TIA!

**Comment by hrishikeshjain** [comment]
@pacocoursey - bump on this, please put on a new release so that we can use cmdk on React < 18 version.

**Comment by mt-deva** [comment]
@pacocoursey - another bump - waiting on this as we're stuck on react@17

**Comment by gnapse** [comment]
It's indeed such a pity that this is still stuck without a release. I had to go with [an alternative](https://ariakit.org/examples/dialog-combobox-command-menu), but I'm still hoping to try this one out. The fact that this library is explicitly about this use case makes me hope it'll be better than what I'm using now.

**Pull request merged**
