### PR TITLE
Add onOpenAutoFocus prop to Dialog component

### PR DESCRIPTION
**Pull request by menachem1**

### CODE REVIEW

**Comment by pacocoursey** [comment]
Could be nice, but I worry about putting these props on the root component rather than just exposing each part of the Dialog instead.

**Comment by menachem1** [comment]
Can you merge this until then?

**Comment by pacocoursey** [comment]
>  Can you merge this until then?

No. One-off requests like this is how a library gets very messy. Let's solve the base problem.

**Comment by menachem1** [comment]
👍

**Pull request closed without merging**
